/** Original CoachRank business self-assessment, version 1. No population norms. */
export const BRAND_ASSESSMENT = {
  slug: "brand-clarity",
  name: "Brand Clarity Assessment",
  version: 1,
  priceCents: 900,
  currency: "USD",
  access: "lifetime",
} as const;

export const BRAND_DIMENSIONS = [
  { id: "audience", label: "Audience", subtitle: "Know whose problem you solve.", insight: "A specific audience helps you choose relevant examples, useful channels and language people recognize.", exercise: "Talk to three people who resemble your intended customer. Ask about the last time they faced the problem, what they tried and what happened. Record their exact words without pitching.", deliverable: "A one-paragraph audience description, three recurring problems and the evidence behind each.", article: "brand-clarity-before-brand-identity" },
  { id: "offer", label: "Offer", subtitle: "Make the exchange easy to understand.", insight: "An offer becomes easier to evaluate when its outcome, scope, limits and next step are visible together.", exercise: "Write a one-page offer with the customer's starting situation, the work included, an observable outcome, a timeframe, price and exclusions. Ask a potential buyer to explain it back.", deliverable: "One offer page that a new reader can accurately explain without your help.", article: "brand-clarity-before-brand-identity" },
  { id: "difference", label: "Difference", subtitle: "Give people a reason to choose.", insight: "Useful differentiation explains a tradeoff. It shows where your approach fits and what a customer gives up by choosing it.", exercise: "Compare your offer with three real alternatives, including doing nothing or doing it themselves. Choose one difference a customer values and write the tradeoff that comes with it.", deliverable: "A comparison table and one specific, supportable reason to choose your approach.", article: "brand-clarity-before-brand-identity" },
  { id: "proof", label: "Proof", subtitle: "Show what supports your promises.", insight: "Trust grows when a claim has nearby evidence, with enough context for a reader to judge its relevance.", exercise: "Choose your three strongest claims. Attach a work sample, a permissioned customer example or a transparent demonstration to each. Include the starting point, your contribution and the limitations.", deliverable: "Three claim-and-evidence pairs you can publish honestly and with permission.", article: "better-feedback-without-taking-over" },
  { id: "message", label: "Message", subtitle: "Say the same clear thing everywhere.", insight: "A coherent message reduces the work people must do to connect your profile, website and offer.", exercise: "Write three versions of your introduction: one sentence, a short paragraph and a profile bio. Use the same audience, problem and outcome. Ask someone unfamiliar with your work to summarize each.", deliverable: "A consistent introduction and a list of confusing words to replace.", article: "creative-work-needs-a-better-feedback-loop" },
  { id: "visibility", label: "Visibility", subtitle: "Create a path from discovery to action.", insight: "Useful visibility reaches relevant people and gives them an obvious, measurable next step.", exercise: "Choose one place your intended customers already use. Publish one useful answer to a recurring question, link it to a relevant offer and record visits, inquiries and what those inquiries ask for.", deliverable: "One distribution channel, one useful piece and a simple inquiry log.", article: "protect-your-attention-without-a-perfect-routine" },
] as const;

export type BrandDimensionId = (typeof BRAND_DIMENSIONS)[number]["id"];
type Question = { id: string; dimension: BrandDimensionId; prompt: string; options: readonly [string, string, string, string]; action: string; hint: string; example: string };

export const BRAND_QUESTIONS: readonly Question[] = [
  { id: "audience-1", hint: "A customer description becomes useful when it includes a situation that makes your help relevant now. Think about the offer you want to assess, rather than every person you could ever help.", example: "“Business owners” is broad. “Solo consultants whose referral work has slowed and who need a repeatable way to win projects” describes a situation and a reason to act.", dimension: "audience", prompt: "How specifically have you defined your primary customer?", options: ["I describe them as anyone who could benefit.", "I name a broad group, such as founders or coaches.", "I name a group and a particular situation or problem.", "I name a specific group, problem and buying trigger, supported by conversations."], action: "Replace a broad audience label with a specific situation: who is experiencing what problem, and why does it matter now?" },
  { id: "audience-2", hint: "Use the last 90 days as a consistent reference point. Conversations, interview notes, inquiry emails and buying behavior all count. A guess about what customers want is different from hearing or observing it.", example: "You might have notes from five discovery calls showing that clients struggle with the same handover problem. A follower liking your post gives much less information about that problem.", dimension: "audience", prompt: "What have you learned directly from potential or current customers recently?", options: ["I mainly rely on my own assumptions.", "I have informal comments but no recorded patterns.", "I have recorded conversations and can name recurring problems.", "I regularly compare customer conversations with actual inquiries or purchases."], action: "Arrange three customer conversations and record recurring problems before deciding what to say about your offer." },
  { id: "audience-3", hint: "A priority problem is something the customer wants to address before other problems. Look for urgency, workarounds or commitment, not just agreement that an idea sounds useful.", example: "A founder saying “I should improve my brand someday” differs from booking time or paying to fix a confusing offer before next month’s launch.", dimension: "audience", prompt: "How do you know which problem your audience wants to solve first?", options: ["I have not chosen a priority problem.", "I chose the problem I most enjoy solving.", "Potential customers have described its urgency and current workarounds.", "Customers have committed money or meaningful effort to solving it."], action: "Ask what the problem currently costs in time or effort and what the person has already tried to change." },
  { id: "audience-4", hint: "Fit criteria explain who can benefit from your offer and who needs something else. They help you say no thoughtfully and make delivery more predictable.", example: "A launch coach might work with founders who already have customer interviews, and refer people who still need to choose a business idea to a different resource.", dimension: "audience", prompt: "How clearly can you identify a customer who is not a good fit?", options: ["I try to serve everyone who asks.", "I decide case by case without clear criteria.", "I have written fit and non-fit criteria.", "I use those criteria in inquiries and review them against delivery experience."], action: "Write two situations where your offer helps and two where a different option would serve the customer better." },
  { id: "offer-1", hint: "Imagine someone landing on your offer page without an introduction from you. What can they understand from the page itself?", example: "A “Brand Strategy Sprint” becomes more concrete when the page says who it serves, what will be delivered, how long it takes and how to begin.", dimension: "offer", prompt: "What does a new visitor learn about your main offer?", options: ["My skills or interests, but no specific offer.", "A service name with a broad promise.", "A defined service, intended customer and outcome.", "The customer, outcome, scope, timeframe and next step in one place."], action: "Put your main offer on one page with its scope, intended customer, timeframe and next step." },
  { id: "offer-2", hint: "A result is what becomes different for the buyer. Activities describe what you do. Both matter, but a buyer should be able to recognize the intended outcome and its limits.", example: "“Four coaching calls” describes an activity. “Leave with a written offer, a customer interview plan and a revised introduction” names things the buyer can use.", dimension: "offer", prompt: "How do you describe the result of buying from you?", options: ["With general words such as transformation or success.", "With a list of activities or sessions.", "With a concrete change or deliverable the buyer can recognize.", "With an observable result, its limits and what the buyer must contribute."], action: "Replace an abstract promise with something a buyer can inspect, use or observe, and explain the limits." },
  { id: "offer-3", hint: "Clear pricing can be a fixed price or a transparent quotation process. You do not need to publish one universal fee for genuinely custom work.", example: "A designer can explain what a starting package includes, what changes the quote and whether revisions or extra pages cost more.", dimension: "offer", prompt: "How easy is it to understand your price and scope?", options: ["Neither is defined yet.", "They change in conversation without a clear starting point.", "The price or quote process and inclusions are explained.", "Inclusions, exclusions, price or quote process, and possible additional costs are clear."], action: "Document inclusions, exclusions and the pricing or quotation process so expectations can be compared before purchase." },
  { id: "offer-4", hint: "Interest, understanding and commitment are different signals. Choose the strongest evidence you actually have for this particular offer.", example: "“Looks great” is encouraging. A person explaining the scope accurately and asking when they can start tells you more. A purchase adds another kind of evidence.", dimension: "offer", prompt: "What evidence tells you the offer makes sense to a buyer?", options: ["I have not shown it to potential customers.", "People have said it looks interesting.", "Potential customers can explain it back and ask relevant buying questions.", "People have bought or made a concrete commitment, and I track their objections."], action: "Show the offer to a likely buyer and ask them to explain what they would receive before asking whether they like it." },
  { id: "difference-1", hint: "An alternative is anything a customer could use instead of your offer. Include doing it themselves, an internal employee, a simpler tool or postponing the decision.", example: "For a productivity coach, alternatives might include a planning app, a manager’s support, a course or continuing with the current routine.", dimension: "difference", prompt: "How well do you understand the alternatives your customer considers?", options: ["I have not examined alternatives.", "I know a few competitors by name.", "I compare their offers, including doing nothing or doing it themselves.", "I record why real prospects choose each alternative and update my comparison."], action: "Compare your offer with competitors, a do-it-yourself approach and doing nothing from the customer's perspective." },
  { id: "difference-2", hint: "A useful difference matters to a specific customer and can be explained concretely. Effort, passion and quality are hard to compare on their own.", example: "“I care deeply” is difficult to verify before purchase. Experience solving a particular problem, a distinctive process or a well-defined specialization gives someone more to evaluate.", dimension: "difference", prompt: "What is your main reason for being chosen?", options: ["I have not defined one.", "Generic qualities such as passion, quality or dedication.", "A specific approach, specialization or experience relevant to the customer.", "A specific difference that customers have independently named as valuable."], action: "Ask a customer what they would miss if they used another option; look for a specific difference you can support." },
  { id: "difference-3", hint: "This asks what someone can inspect to understand your difference, rather than whether you can write an impressive claim.", example: "If you promise unusually clear feedback, show a realistic annotated example of the feedback a client would receive. Explain the example’s scope.", dimension: "difference", prompt: "How is your difference demonstrated?", options: ["It is only a claim.", "I explain it verbally when asked.", "I show a process, example or comparison.", "I show evidence of the difference and explain where it does and does not help."], action: "Publish a small demonstration of your approach so someone can inspect the claimed difference." },
  { id: "difference-4", hint: "A tradeoff is a deliberate choice about what you prioritize. It helps people understand fit. It is not an invitation to invent a weakness.", example: "A focused two-week sprint may prioritize speed and a narrow deliverable over comprehensive long-term support. Both approaches can be useful for different buyers.", dimension: "difference", prompt: "How clearly have you chosen a tradeoff?", options: ["I promise to be better at everything.", "I have preferences but do not explain them.", "I can explain what I prioritize and what I do not provide.", "The tradeoff shapes my offer and helps customers decide whether it fits."], action: "Finish this sentence honestly: we prioritize this, which means we are not the best choice for that." },
  { id: "proof-1", hint: "Look at the evidence next to your strongest claims. Evidence should support the particular promise, not just demonstrate that you are experienced in general.", example: "If your offer promises a clear action plan, show an actual or clearly labeled sample plan. A certificate alone does not demonstrate the plan’s quality.", dimension: "proof", prompt: "What supports the claims on your website or profile?", options: ["Mostly adjectives and promises.", "Credentials or experience, with little connection to the specific claims.", "Relevant examples or demonstrations next to important claims.", "Relevant examples include context, limitations and a clear connection to each claim."], action: "Place a relevant example beside your strongest claim, explaining the context and what it actually demonstrates." },
  { id: "proof-2", hint: "A useful sample lets someone experience a small, representative part of your work before buying. New businesses can create original demonstrations without inventing clients.", example: "A consultant could publish a sample diagnostic. A coach could share a question framework. Label fictional examples and explain what is included in the paid version.", dimension: "proof", prompt: "How do you show your work if someone has not bought from you yet?", options: ["They cannot see an example.", "I describe past work without showing it.", "They can inspect a useful sample, walkthrough or demonstration.", "The sample reflects the paid experience and explains what the buyer receives."], action: "Create a small sample that represents the quality and format of the paid experience." },
  { id: "proof-3", hint: "You do not need testimonials to answer well. Honest demonstrations are valid evidence. Customer feedback needs permission and enough context to avoid misleading the reader.", example: "A short customer quote used with permission can help. If you do not have customers yet, show a clearly labeled example of your process instead of implying it is a client result.", dimension: "proof", prompt: "How do you handle testimonials or customer stories?", options: ["I have no evidence collection or permission process.", "I keep positive comments but have not confirmed permission to publish.", "I use permissioned feedback with accurate context, or clearly labeled original demonstrations.", "I maintain permissioned, contextual evidence and review whether it supports my current offer."], action: "Ask permission before using customer feedback. If you have none, publish an original demonstration labeled as an example." },
  { id: "proof-4", hint: "Every offer has conditions, limits and responsibilities. This asks how easily a buyer can see them before purchasing.", example: "An offer might explain that it provides a messaging plan, does not include logo design, and needs the buyer to bring customer research.", dimension: "proof", prompt: "How does a prospective buyer assess the limits of your promise?", options: ["I mainly describe ideal outcomes.", "I explain limitations only when asked.", "I explain dependencies, scope and who is not a fit.", "Those limits appear alongside the offer and are reinforced before purchase."], action: "Add a short fit-and-limitations section to the offer so a buyer can make an informed decision." },
  { id: "message-1", hint: "Compare the core meaning across your main touchpoints. The wording can vary, but the audience, problem and offer should be recognizable.", example: "If your profile sells executive coaching and your website mainly offers website design, a visitor may not know which business they have found.", dimension: "message", prompt: "How closely do your website, profile and offer describe the same business?", options: ["They present different audiences or services.", "They overlap, but key wording or promises differ.", "They share an audience, problem and core offer.", "They share those elements and I regularly check links and outdated claims."], action: "Compare the first paragraph on your website, profile and offer; align the audience, problem and next step." },
  { id: "message-2", hint: "Understanding is something you can check. Ask someone unfamiliar with the business to explain it after reading, without helping them arrive at the answer.", example: "After seeing your introduction, can a person say who it serves and what someone would buy? “Sounds inspiring” does not answer those questions.", dimension: "message", prompt: "What happens when someone unfamiliar with your work reads your introduction?", options: ["I have not tested it.", "They often ask what I actually do.", "They can explain the main service and who it helps.", "They can explain it accurately and identify when they would recommend it."], action: "Ask someone unfamiliar with your work what you do, who it helps and when they would recommend it after reading your introduction." },
  { id: "message-3", hint: "Customer language means the words people use to describe their situation. You can use technical terms when your intended customers understand them.", example: "If customers say “people ask for my price and disappear,” that may communicate their problem more clearly than “optimize conversion alignment.”", dimension: "message", prompt: "Where does the language in your messaging come from?", options: ["Mostly jargon or phrases I admire elsewhere.", "My own description of the service.", "A mix of clear descriptions and language customers use.", "Customer language tested for clarity, with ambiguous terms explained or removed."], action: "Replace three abstract phrases with the words customers use to describe their problem." },
  { id: "message-4", hint: "A message guide can be a short document, not a formal brand book. Its job is to keep your core claims consistent while leaving room for fresh writing.", example: "A one-page guide might include your audience, main offer, three examples, preferred terms and promises you cannot support.", dimension: "message", prompt: "How do you keep your message consistent as you create content?", options: ["I improvise every time.", "I reuse some phrases without a shared reference.", "I keep a short guide with my introduction, main promise and examples.", "I use that guide, check understanding and revise it when customer evidence changes."], action: "Create a one-page message guide with your introduction, core promise, examples and phrases to avoid." },
  { id: "visibility-1", hint: "Choose a channel because it gives you access to relevant people in a useful context. Popularity and follower counts are not the same as customer fit.", example: "A founder may discover that a small industry newsletter brings more relevant conversations than a large general social account.", dimension: "visibility", prompt: "How did you choose your main channel for reaching customers?", options: ["I have no main channel.", "I chose it because it is popular or familiar.", "I have evidence my intended audience uses it for relevant questions.", "I have evidence it leads to relevant conversations or customers and review that regularly."], action: "Ask three intended customers where they look for help with the problem and choose one channel to test." },
  { id: "visibility-2", hint: "Look at your most recent work and ask what it helps a likely customer understand or do. Promotion is useful, but a reader also needs a reason to pay attention.", example: "An article answering a recurring buying question, with a relevant sample or next step, can connect education to your offer.", dimension: "visibility", prompt: "What does your recent content help a potential buyer do?", options: ["There is little content or no clear connection to the offer.", "It mainly announces or promotes my services.", "It answers recurring customer questions with useful examples.", "It answers those questions and leads naturally to a relevant, clear next step."], action: "Publish a useful answer to one recurring customer question, then connect it to the appropriate next step." },
  { id: "visibility-3", hint: "Follow the actual path a person takes from finding you to contacting, booking or buying. Check the destination, form, confirmation and expectations.", example: "Open your profile on a phone, follow the link, and try the next step. Is it obvious what happens after an inquiry, and does the confirmation arrive?", dimension: "visibility", prompt: "How easy is it to take the next step after finding you?", options: ["There is no obvious action or the link is broken.", "People must search for a way to contact or buy.", "There is a working, clearly described next step.", "I have tested that step on mobile and desktop and explain what happens afterward."], action: "Follow your own discovery-to-inquiry path on a phone; remove a confusing step and explain what happens after submission." },
  { id: "visibility-4", hint: "Useful measurement connects attention to relevant conversations or purchases. A simple manual log is enough to start; you do not need an elaborate analytics stack.", example: "Record where each inquiry came from, what the person needed and what happened next. That reveals more about fit than a total view count alone.", dimension: "visibility", prompt: "What do you track to judge whether your visibility is useful?", options: ["I do not track it.", "Mostly followers, views or likes.", "Relevant inquiries and where they came from.", "The path from content to inquiry to purchase, including fit and objections."], action: "Start a simple log of relevant inquiries, their source and whether they became a useful conversation or purchase." },
];

export type BrandAnswers = Record<string, number>;
export function validBrandAnswers(value: unknown, complete = false): value is BrandAnswers {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const entries = Object.entries(value);
  if (complete && entries.length !== BRAND_QUESTIONS.length) return false;
  return entries.every(([key, answer]) => BRAND_QUESTIONS.some(question => question.id === key) && Number.isInteger(answer) && answer >= 0 && answer <= 3);
}

export function brandReport(answers: BrandAnswers) {
  if (!validBrandAnswers(answers, true)) throw new Error("Answer all 24 questions before creating your report.");
  const dimensions = BRAND_DIMENSIONS.map(dimension => {
    const questions = BRAND_QUESTIONS.filter(question => question.dimension === dimension.id);
    const score = Math.round(questions.reduce((sum, question) => sum + answers[question.id], 0) / (questions.length * 3) * 100);
    const weakest = [...questions].sort((a, b) => answers[a.id] - answers[b.id])[0];
    return { ...dimension, score, band: score < 40 ? "Build the foundation" : score < 70 ? "Develop the evidence" : "Maintain and test", question: weakest.prompt, answer: weakest.options[answers[weakest.id]], action: score === 100 ? "Revisit this area with a new customer and check whether the evidence still supports your answers." : weakest.action };
  });
  const priorities = [...dimensions].sort((a, b) => a.score - b.score).slice(0, 3);
  return { dimensions, priorities, established: dimensions.every(dimension => dimension.score >= 70) };
}

export type BrandReport = ReturnType<typeof brandReport>;
export const SAMPLE_ANSWERS: BrandAnswers = Object.fromEntries(BRAND_QUESTIONS.map((question, index) => [question.id, [2, 2, 1, 2, 3, 2, 2, 2, 1, 1, 0, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 0, 1, 1][index]]));

export function brandActionPlan(report: BrandReport) {
  const [first, second, third] = report.priorities;
  return [
    { day: "01", title: "Start with the evidence", task: `Review the answers behind ${first.label.toLowerCase()}. Collect the notes, pages or examples that support them. Write down what is still an assumption.`, outcome: "A short evidence-and-assumptions list." },
    { day: "02", title: `Work on ${first.label.toLowerCase()}`, task: first.exercise, outcome: first.deliverable },
    { day: "03", title: "Test your first change", task: `Use this specific next step: ${first.action} Ask a relevant person what is clearer and what still needs explanation.`, outcome: "One revised artifact and one observation from someone outside the business." },
    { day: "04", title: `Make progress on ${second.label.toLowerCase()}`, task: second.exercise, outcome: second.deliverable },
    { day: "05", title: `Your third priority: ${third.label}`, task: third.exercise, outcome: third.deliverable },
    { day: "06", title: "Connect the changes", task: "Check that your audience, offer, evidence and next step tell the same story. Ask a likely customer to follow the journey from discovering you to making an inquiry. Record where they pause.", outcome: "A list of friction points, with one fixed today." },
    { day: "07", title: "Review what actually changed", task: "Compare your original assumptions with what you learned. Keep the changes supported by feedback. Choose one experiment for the next week, then take another assessment when you have new evidence.", outcome: "One next experiment, a review date and a reason for choosing it." },
  ];
}
