/** Original CoachRank business self-assessment, version 1. No population norms. */
export const BRAND_ASSESSMENT = {
  slug: "brand-clarity",
  name: "Brand Clarity Assessment",
  version: 1,
  priceCents: 900,
  currency: "USD",
  retakeDays: 30,
} as const;

export const BRAND_DIMENSIONS = [
  { id: "audience", label: "Audience", subtitle: "Know whose problem you solve.", insight: "A specific audience helps you choose relevant examples, useful channels and language people recognize.", exercise: "Talk to three people who resemble your intended customer. Ask about the last time they faced the problem, what they tried and what happened. Record their exact words without pitching.", deliverable: "A one-paragraph audience description, three recurring problems and the evidence behind each.", article: "brand-clarity-before-brand-identity" },
  { id: "offer", label: "Offer", subtitle: "Make the exchange easy to understand.", insight: "An offer becomes easier to evaluate when its outcome, scope, limits and next step are visible together.", exercise: "Write a one-page offer with the customer's starting situation, the work included, an observable outcome, a timeframe, price and exclusions. Ask a potential buyer to explain it back.", deliverable: "One offer page that a new reader can accurately explain without your help.", article: "brand-clarity-before-brand-identity" },
  { id: "difference", label: "Difference", subtitle: "Give people a reason to choose.", insight: "Useful differentiation explains a tradeoff. It shows where your approach fits and what a customer gives up by choosing it.", exercise: "Compare your offer with three real alternatives, including doing nothing or doing it themselves. Choose one difference a customer values and write the tradeoff that comes with it.", deliverable: "A comparison table and one specific, supportable reason to choose your approach.", article: "brand-clarity-before-brand-identity" },
  { id: "proof", label: "Proof", subtitle: "Show what supports your promises.", insight: "Trust grows when a claim has nearby evidence, with enough context for a reader to judge its relevance.", exercise: "Choose your three strongest claims. Attach a work sample, a permissioned customer example or a transparent demonstration to each. Include the starting point, your contribution and the limitations.", deliverable: "Three claim-and-evidence pairs you can publish honestly and with permission.", article: "better-feedback-without-taking-over" },
  { id: "message", label: "Message", subtitle: "Say the same clear thing everywhere.", insight: "A coherent message reduces the work people must do to connect your profile, website and offer.", exercise: "Write three versions of your introduction: one sentence, a short paragraph and a profile bio. Use the same audience, problem and outcome. Ask someone unfamiliar with your work to summarize each.", deliverable: "A consistent introduction and a list of confusing words to replace.", article: "creative-work-needs-a-better-feedback-loop" },
  { id: "visibility", label: "Visibility", subtitle: "Create a path from discovery to action.", insight: "Useful visibility reaches relevant people and gives them an obvious, measurable next step.", exercise: "Choose one place your intended customers already use. Publish one useful answer to a recurring question, link it to a relevant offer and record visits, inquiries and what those inquiries ask for.", deliverable: "One distribution channel, one useful piece and a simple inquiry log.", article: "protect-your-attention-without-a-perfect-routine" },
] as const;

export type BrandDimensionId = (typeof BRAND_DIMENSIONS)[number]["id"];
type Question = { id: string; dimension: BrandDimensionId; prompt: string; options: readonly [string, string, string, string]; action: string };

export const BRAND_QUESTIONS: readonly Question[] = [
  { id: "audience-1", dimension: "audience", prompt: "How specifically have you defined your primary customer?", options: ["I describe them as anyone who could benefit.", "I name a broad group, such as founders or coaches.", "I name a group and a particular situation or problem.", "I name a specific group, problem and buying trigger, supported by conversations."], action: "Replace a broad audience label with a specific situation: who is experiencing what problem, and why does it matter now?" },
  { id: "audience-2", dimension: "audience", prompt: "What have you learned directly from potential or current customers recently?", options: ["I mainly rely on my own assumptions.", "I have informal comments but no recorded patterns.", "I have recorded conversations and can name recurring problems.", "I regularly compare customer conversations with actual inquiries or purchases."], action: "Arrange three customer conversations and record recurring problems before deciding what to say about your offer." },
  { id: "audience-3", dimension: "audience", prompt: "How do you know which problem your audience wants to solve first?", options: ["I have not chosen a priority problem.", "I chose the problem I most enjoy solving.", "Potential customers have described its urgency and current workarounds.", "Customers have committed money or meaningful effort to solving it."], action: "Ask what the problem currently costs in time or effort and what the person has already tried to change." },
  { id: "audience-4", dimension: "audience", prompt: "How clearly can you identify a customer who is not a good fit?", options: ["I try to serve everyone who asks.", "I decide case by case without clear criteria.", "I have written fit and non-fit criteria.", "I use those criteria in inquiries and review them against delivery experience."], action: "Write two situations where your offer helps and two where a different option would serve the customer better." },
  { id: "offer-1", dimension: "offer", prompt: "What does a new visitor learn about your main offer?", options: ["My skills or interests, but no specific offer.", "A service name with a broad promise.", "A defined service, intended customer and outcome.", "The customer, outcome, scope, timeframe and next step in one place."], action: "Put your main offer on one page with its scope, intended customer, timeframe and next step." },
  { id: "offer-2", dimension: "offer", prompt: "How do you describe the result of buying from you?", options: ["With general words such as transformation or success.", "With a list of activities or sessions.", "With a concrete change or deliverable the buyer can recognize.", "With an observable result, its limits and what the buyer must contribute."], action: "Replace an abstract promise with something a buyer can inspect, use or observe, and explain the limits." },
  { id: "offer-3", dimension: "offer", prompt: "How easy is it to understand your price and scope?", options: ["Neither is defined yet.", "They change in conversation without a clear starting point.", "The price or quote process and inclusions are explained.", "Inclusions, exclusions, price or quote process, and possible additional costs are clear."], action: "Document inclusions, exclusions and the pricing or quotation process so expectations can be compared before purchase." },
  { id: "offer-4", dimension: "offer", prompt: "What evidence tells you the offer makes sense to a buyer?", options: ["I have not shown it to potential customers.", "People have said it looks interesting.", "Potential customers can explain it back and ask relevant buying questions.", "People have bought or made a concrete commitment, and I track their objections."], action: "Show the offer to a likely buyer and ask them to explain what they would receive before asking whether they like it." },
  { id: "difference-1", dimension: "difference", prompt: "How well do you understand the alternatives your customer considers?", options: ["I have not examined alternatives.", "I know a few competitors by name.", "I compare their offers, including doing nothing or doing it themselves.", "I record why real prospects choose each alternative and update my comparison."], action: "Compare your offer with competitors, a do-it-yourself approach and doing nothing from the customer's perspective." },
  { id: "difference-2", dimension: "difference", prompt: "What is your main reason for being chosen?", options: ["I have not defined one.", "Generic qualities such as passion, quality or dedication.", "A specific approach, specialization or experience relevant to the customer.", "A specific difference that customers have independently named as valuable."], action: "Ask a customer what they would miss if they used another option; look for a specific difference you can support." },
  { id: "difference-3", dimension: "difference", prompt: "How is your difference demonstrated?", options: ["It is only a claim.", "I explain it verbally when asked.", "I show a process, example or comparison.", "I show evidence of the difference and explain where it does and does not help."], action: "Publish a small demonstration of your approach so someone can inspect the claimed difference." },
  { id: "difference-4", dimension: "difference", prompt: "How clearly have you chosen a tradeoff?", options: ["I promise to be better at everything.", "I have preferences but do not explain them.", "I can explain what I prioritize and what I do not provide.", "The tradeoff shapes my offer and helps customers decide whether it fits."], action: "Finish this sentence honestly: we prioritize this, which means we are not the best choice for that." },
  { id: "proof-1", dimension: "proof", prompt: "What supports the claims on your website or profile?", options: ["Mostly adjectives and promises.", "Credentials or experience, with little connection to the specific claims.", "Relevant examples or demonstrations next to important claims.", "Relevant examples include context, limitations and a clear connection to each claim."], action: "Place a relevant example beside your strongest claim, explaining the context and what it actually demonstrates." },
  { id: "proof-2", dimension: "proof", prompt: "How do you show your work if someone has not bought from you yet?", options: ["They cannot see an example.", "I describe past work without showing it.", "They can inspect a useful sample, walkthrough or demonstration.", "The sample reflects the paid experience and explains what the buyer receives."], action: "Create a small sample that represents the quality and format of the paid experience." },
  { id: "proof-3", dimension: "proof", prompt: "How do you handle testimonials or customer stories?", options: ["I have no evidence collection or permission process.", "I keep positive comments but have not confirmed permission to publish.", "I use permissioned feedback with accurate context, or clearly labeled original demonstrations.", "I maintain permissioned, contextual evidence and review whether it supports my current offer."], action: "Ask permission before using customer feedback. If you have none, publish an original demonstration labeled as an example." },
  { id: "proof-4", dimension: "proof", prompt: "How does a prospective buyer assess the limits of your promise?", options: ["I mainly describe ideal outcomes.", "I explain limitations only when asked.", "I explain dependencies, scope and who is not a fit.", "Those limits appear alongside the offer and are reinforced before purchase."], action: "Add a short fit-and-limitations section to the offer so a buyer can make an informed decision." },
  { id: "message-1", dimension: "message", prompt: "How closely do your website, profile and offer describe the same business?", options: ["They present different audiences or services.", "They overlap, but key wording or promises differ.", "They share an audience, problem and core offer.", "They share those elements and I regularly check links and outdated claims."], action: "Compare the first paragraph on your website, profile and offer; align the audience, problem and next step." },
  { id: "message-2", dimension: "message", prompt: "What happens when someone unfamiliar with your work reads your introduction?", options: ["I have not tested it.", "They often ask what I actually do.", "They can explain the main service and who it helps.", "They can explain it accurately and identify when they would recommend it."], action: "Ask someone unfamiliar with your work what you do, who it helps and when they would recommend it after reading your introduction." },
  { id: "message-3", dimension: "message", prompt: "Where does the language in your messaging come from?", options: ["Mostly jargon or phrases I admire elsewhere.", "My own description of the service.", "A mix of clear descriptions and language customers use.", "Customer language tested for clarity, with ambiguous terms explained or removed."], action: "Replace three abstract phrases with the words customers use to describe their problem." },
  { id: "message-4", dimension: "message", prompt: "How do you keep your message consistent as you create content?", options: ["I improvise every time.", "I reuse some phrases without a shared reference.", "I keep a short guide with my introduction, main promise and examples.", "I use that guide, check understanding and revise it when customer evidence changes."], action: "Create a one-page message guide with your introduction, core promise, examples and phrases to avoid." },
  { id: "visibility-1", dimension: "visibility", prompt: "How did you choose your main channel for reaching customers?", options: ["I have no main channel.", "I chose it because it is popular or familiar.", "I have evidence my intended audience uses it for relevant questions.", "I have evidence it leads to relevant conversations or customers and review that regularly."], action: "Ask three intended customers where they look for help with the problem and choose one channel to test." },
  { id: "visibility-2", dimension: "visibility", prompt: "What does your recent content help a potential buyer do?", options: ["There is little content or no clear connection to the offer.", "It mainly announces or promotes my services.", "It answers recurring customer questions with useful examples.", "It answers those questions and leads naturally to a relevant, clear next step."], action: "Publish a useful answer to one recurring customer question, then connect it to the appropriate next step." },
  { id: "visibility-3", dimension: "visibility", prompt: "How easy is it to take the next step after finding you?", options: ["There is no obvious action or the link is broken.", "People must search for a way to contact or buy.", "There is a working, clearly described next step.", "I have tested that step on mobile and desktop and explain what happens afterward."], action: "Follow your own discovery-to-inquiry path on a phone; remove a confusing step and explain what happens after submission." },
  { id: "visibility-4", dimension: "visibility", prompt: "What do you track to judge whether your visibility is useful?", options: ["I do not track it.", "Mostly followers, views or likes.", "Relevant inquiries and where they came from.", "The path from content to inquiry to purchase, including fit and objections."], action: "Start a simple log of relevant inquiries, their source and whether they became a useful conversation or purchase." },
];

export type BrandAnswers = Record<string, number>;
export function validBrandAnswers(value: unknown, complete = false): value is BrandAnswers {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const entries = Object.entries(value);
  if (complete && entries.length !== BRAND_QUESTIONS.length) return false;
  return entries.every(([key, answer]) => BRAND_QUESTIONS.some(question => question.id === key) && Number.isInteger(answer) && answer >= 0 && answer <= 3);
}

export function brandReport(answers: BrandAnswers) {
  if (!validBrandAnswers(answers, true)) throw new Error("Answer all 24 questions before creating your report.");
  const dimensions = BRAND_DIMENSIONS.map(dimension => {
    const questions = BRAND_QUESTIONS.filter(question => question.dimension === dimension.id);
    const score = Math.round(questions.reduce((sum, question) => sum + answers[question.id], 0) / (questions.length * 3) * 100);
    const weakest = [...questions].sort((a, b) => answers[a.id] - answers[b.id])[0];
    return { ...dimension, score, band: score < 40 ? "Build the foundation" : score < 70 ? "Develop the evidence" : "Maintain and test", question: weakest.prompt, answer: weakest.options[answers[weakest.id]], action: score === 100 ? "Revisit this area with a new customer and check whether the evidence still supports your answers." : weakest.action };
  });
  const priorities = [...dimensions].sort((a, b) => a.score - b.score).slice(0, 3);
  return { dimensions, priorities, established: dimensions.every(dimension => dimension.score >= 70) };
}

export type BrandReport = ReturnType<typeof brandReport>;
export const SAMPLE_ANSWERS: BrandAnswers = Object.fromEntries(BRAND_QUESTIONS.map((question, index) => [question.id, [2, 2, 1, 2, 3, 2, 2, 2, 1, 1, 0, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 0, 1, 1][index]]));

export function brandActionPlan(report: BrandReport) {
  const [first, second, third] = report.priorities;
  return [
    { day: "01", title: "Start with the evidence", task: `Review the answers behind ${first.label.toLowerCase()}. Collect the notes, pages or examples that support them. Write down what is still an assumption.`, outcome: "A short evidence-and-assumptions list." },
    { day: "02", title: `Work on ${first.label.toLowerCase()}`, task: first.exercise, outcome: first.deliverable },
    { day: "03", title: "Test your first change", task: `Use this specific next step: ${first.action} Ask a relevant person what is clearer and what still needs explanation.`, outcome: "One revised artifact and one observation from someone outside the business." },
    { day: "04", title: `Make progress on ${second.label.toLowerCase()}`, task: second.exercise, outcome: second.deliverable },
    { day: "05", title: `Your third priority: ${third.label}`, task: third.exercise, outcome: third.deliverable },
    { day: "06", title: "Connect the changes", task: "Check that your audience, offer, evidence and next step tell the same story. Ask a likely customer to follow the journey from discovering you to making an inquiry. Record where they pause.", outcome: "A list of friction points, with one fixed today." },
    { day: "07", title: "Review what actually changed", task: "Compare your original assumptions with what you learned. Keep the changes supported by feedback. Choose one experiment for the next week, then use your included reassessment when you have new evidence.", outcome: "One next experiment, a review date and a reason for choosing it." },
  ];
}
