import Link from "next/link";
import {getAdminUser} from "@/lib/admin-auth";
import {buyingJourneyReport} from "@/lib/domain/buying-journeys";
import {JOURNEY_STAGES} from "@/lib/buying-journey";
import {formatCents} from "@/lib/money";
export const dynamic="force-dynamic";
const labels={article_view:"Read an article",product_view:"Viewed the product",sample_view:"Viewed the sample",sign_in_view:"Opened sign-in",sign_in_completed:"Completed sign-in",checkout_started:"Opened checkout",purchase_confirmed:"Payment confirmed",report_completed:"Completed a report"};
export default async function BuyingJourneyPage(){
 if(!await getAdminUser())return null;
 let data;try{data=await buyingJourneyReport();}catch{return <div className="admin-page-heading"><h1>Buying journey</h1><p role="alert">Measurement data is unavailable. Reload to try again. This does not mean there were no visits or sales.</p></div>;}
 const tables=[{title:"Where journeys started",column:"Source / campaign / post",rows:data.sources},{title:"First article read",column:"Article",rows:data.articles}];
 return <div><div className="admin-page-heading"><div><p className="journal-label">From discovery to a useful result</p><h1>Buying journey</h1><p>Journeys and orders started in the last {data.days} days. Updates appear when you reload.</p></div><Link href="/admin/tools" className="tool-text-link">Tools & feedback ↗</Link></div>
 <div className="admin-metrics">{[{label:"Recorded journeys",value:Math.min(data.count,5000),detail:"One browser journey lasts up to 30 days"},{label:"Paid orders",value:data.paid,detail:"Verified, excluding previews and reversals"},{label:"Revenue before tax and fees",value:formatCents(data.revenueCents),detail:"Paid orders started in this period"},{label:"Buyers with a report",value:data.completed,detail:"Paid orders with at least one saved report"}].map(x=><div className="admin-metric" key={x.label}><p>{x.label}</p><strong>{x.value}</strong><span>{x.detail}</span></div>)}</div>
 {data.limited&&<p role="alert" className="tool-notice">This view is limited to the latest 5,000 journeys and 5,000 orders. Counts are partial.</p>}
 <section className="journey-section"><h2>Steps reached</h2><p>Each journey counts once per step. People can skip steps or return later, so these are reach counts, not a strict sequential conversion rate. Product visits include visitors who are already signed in. Sign-in may be for a returning purchase.</p><ol className="journey-stages">{JOURNEY_STAGES.map(stage=><li key={stage}><span>{labels[stage]}</span><strong>{data.stages[stage]}</strong></li>)}</ol></section>
 {tables.map(table=><section className="journey-section" key={table.title}><h2>{table.title}</h2>{table.rows.length?<div className="journey-table-wrap"><table className="journey-table"><thead><tr>{[table.column,"Journeys","Product","Checkout","Payment","Report"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{table.rows.map(row=><tr key={row.label}><th scope="row">{row.label.startsWith("/blog/")?<Link href={row.label}>{row.label.slice(6)}</Link>:row.label}</th><td>{row.journeys}</td><td>{row.product}</td><td>{row.checkout}</td><td>{row.purchase}</td><td>{row.report}</td></tr>)}</tbody></table></div>:<p>No journeys recorded yet. Share a tagged link to begin measuring.</p>}</section>)}
 <section className="journey-section"><h2>How to read these numbers</h2><p>Source credit stays with the first recorded visit for 30 days. The article table credits the first article read in that journey. A payment and report are attached to the journey saved when checkout was created, even if the buyer finishes on another device. Historical orders and visits without a measurement cookie may have no source.</p><p>{data.unattributedPaid} paid orders have no matching journey in this period. {data.reversed} orders were reversed. The steps and source tables retain confirmed payment events after reversal; the paid-order and revenue totals exclude reversed orders.</p><p>Only verified server records can count a checkout, payment or completed report. Browser page views are approximate and can be missed or automated. Admin sessions, previews, opt-outs and browser privacy signals are excluded from page measurement. No email addresses, sign-in links, payment credentials or assessment answers are stored in journey records.</p><p>Tracking began with this release. Earlier traffic is not reconstructed. Journey records are scheduled for deletion after 90 days. <Link href="/privacy">Privacy and browser preference ↗</Link></p></section></div>;
}
