import type {Metadata} from "next";
import Link from "next/link";
import {AssessmentCheckout} from "@/components/AssessmentCheckout";
import {ReportPreview} from "@/components/ReportPreview";
import {DimensionIcon} from "@/components/DimensionIcon";
import {BRAND_DIMENSIONS,BRAND_QUESTIONS} from "@/lib/brand-assessment";
import {absoluteUrl} from "@/lib/config";
import {isAssessmentCheckoutConfigured} from "@/lib/dodo";
import {getCustomerUser} from "@/lib/customer-auth";
import {customerAssessment} from "@/lib/domain/assessments";
import {getPublishedPostBySlug} from "@/lib/domain/blog";
import {jsonLd} from "@/lib/editorial";
export const dynamic="force-dynamic";
const pageTitle="Brand Clarity Assessment | $9 Lifetime Access";
const pageDescription="Assess your audience, offer, difference, proof, message and visibility. Get three priorities and a seven-day plan. $9 once, with unlimited retakes and PDF reports.";
export const metadata:Metadata={title:pageTitle,description:pageDescription,alternates:{canonical:"/tools/brand-clarity"},openGraph:{title:`${pageTitle} · CoachRank`,description:pageDescription,url:absoluteUrl("/tools/brand-clarity"),images:[{url:absoluteUrl("/editorial/edition-03/brand-positioning-statement-examples.webp"),width:1536,height:1024,alt:"Three paths converge on a focused orange marker."}]},twitter:{card:"summary_large_image",title:`${pageTitle} · CoachRank`,description:pageDescription,images:[absoluteUrl("/editorial/edition-03/brand-positioning-statement-examples.webp")]}};
export default async function BrandClarityPage({searchParams}:PageProps<"/tools/brand-clarity">){
 const enabled=isAssessmentCheckoutConfigured();const {checkout}=await searchParams;
 const [user,...guides]=await Promise.all([getCustomerUser(),...[
  "brand-clarity-before-brand-identity","brand-positioning-statement-examples","brand-audit-checklist-small-business"
 ].map(slug=>getPublishedPostBySlug(slug))]);const owned=user?await customerAssessment(user.uid):null;
 const structured={"@context":"https://schema.org","@graph":[{"@type":"Product","@id":absoluteUrl("/tools/brand-clarity#product"),name:"CoachRank Brand Clarity Assessment",description:"24 questions, six visual scores, three next moves, a seven-day plan and a downloadable PDF. Lifetime access with unlimited retakes and report comparisons.",brand:{"@type":"Brand",name:"CoachRank"},image:absoluteUrl("/editorial/edition-03/brand-positioning-statement-examples.webp"),offers:{"@type":"Offer",price:"9.00",priceCurrency:"USD",availability:enabled?"https://schema.org/InStock":"https://schema.org/OutOfStock",url:absoluteUrl("/tools/brand-clarity")}}, {"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"CoachRank",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:"Tools",item:absoluteUrl("/tools")},{"@type":"ListItem",position:3,name:"Brand Clarity Assessment",item:absoluteUrl("/tools/brand-clarity")}]}]};
 return <div className="tools-shell clarity-page"><Link href="/tools" className="tool-back">← CoachRank Tools</Link>{checkout==="cancelled"?<p className="tool-notice" role="status">Checkout was closed. Already paid? Open My tools below to check your purchase.</p>:null}
 <header className="clarity-hero"><div className="clarity-hero-copy"><p className="journal-label"><span className="journal-status-dot"/>CoachRank Tools · Edition 01</p><h1>Brand Clarity<br/><em>Assessment.</em></h1><p className="clarity-dek">Find the gaps in how you explain your business. Leave with three priorities, a seven-day action plan and a visual report you can return to.</p><p className="clarity-audience">For coaches, consultants, founders and personal brands with an offer to clarify. 24 guided questions, about 10 minutes.</p><div className="clarity-hero-actions"><a href="#get-assessment" className="tool-button">Get lifetime access · $9 ↗</a><Link href="/tools/brand-clarity/sample" className="tool-text-link">Explore a complete report</Link></div><div className="clarity-purchase-facts"><span>✓ Pay once</span><span>✓ Unlimited retakes</span><span>✓ Compare your reports</span></div><p className="tool-tax-note">$9 USD plus applicable tax. No subscription.</p></div><ReportPreview/></header>
 <nav className="clarity-page-nav" aria-label="On this page"><a href="#what-is-brand-clarity">What it is</a><a href="#when-to-assess">When it helps</a><a href="#brand-dimensions">What it covers</a><a href="#how-it-works">How it works</a><a href="#get-assessment">Pricing &amp; access</a><a href="#assessment-questions">Questions</a></nav>
 <section className="clarity-explainer" id="what-is-brand-clarity" aria-labelledby="clarity-definition-heading"><div><p className="journal-label">A practical starting point</p><h2 id="clarity-definition-heading">What is a Brand<br/>Clarity Assessment?</h2></div><div><p>A Brand Clarity Assessment is a structured self-review of how clearly you define your audience, explain your offer and support the reasons someone might choose you. It helps you identify what is clear, where you are relying on assumptions and what deserves attention next.</p><p>CoachRank guides you through 24 questions across six dimensions. Your answers become a visual report, three priorities and a seven-day plan. You can save progress, download each report and compare your answers over time.</p><p className="clarity-method-note">The assessment uses your own answers. It does not scan your website, interview your customers or predict sales. Use the report to choose what to investigate and improve.</p></div></section>
 <section className="clarity-use-cases" id="when-to-assess" aria-labelledby="clarity-timing-heading"><div className="tool-section-heading"><p className="journal-label">Why take an assessment?</p><h2 id="clarity-timing-heading">Give your next change<br/>a clearer purpose.</h2><p>For a business or a personal brand, clarity helps people recognize the offer and evaluate whether it fits. These are useful moments to pause and review.</p></div><div className="clarity-use-case-grid">{[
  ["Before a redesign","Clarify the audience, offer and evidence so your new website or identity has a specific job to do."],
  ["When people misunderstand","Find questions worth investigating when prospects cannot explain what you sell or expect something different."],
  ["When your offer changes","Review whether your profiles, pages and examples still describe the work you now want to be known for."],
  ["Before your next promotion","Examine what a new visitor needs to understand before you send more people to the offer."]
 ].map(([title,description],index)=><article key={title}><span className="journal-label">0{index+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
 <section className="clarity-outcomes" aria-label="What your purchase includes"><article><span className="outcome-symbol" aria-hidden="true">↗</span><p className="journal-label">01 / Direction</p><h2>Your next three moves.</h2><p>Understand which gaps deserve attention first, with an answer behind each priority and a concrete action to take.</p></article><article><span className="outcome-symbol" aria-hidden="true">7</span><p className="journal-label">02 / A plan</p><h2>A week with a purpose.</h2><p>Seven work sessions, each with a task and something useful to leave with. Download the report and keep it beside your work.</p></article><article><span className="outcome-symbol" aria-hidden="true">∞</span><p className="journal-label">03 / Perspective</p><h2>Return. Reflect. Compare.</h2><p>Retake whenever you have new evidence. Keep every report and compare any two snapshots side by side.</p></article></section>
 <section className="tool-dimensions" id="brand-dimensions"><div className="tool-section-heading"><p className="journal-label">Six dimensions of a clearer brand</p><h2>What does the assessment cover?</h2><p>Explore the evidence behind what you say, sell and share. Each dimension connects to a decision you can work on.</p></div><div>{BRAND_DIMENSIONS.map(d=><article key={d.id}><DimensionIcon dimension={d.id}/><h3>{d.label}</h3><p>{d.subtitle}</p></article>)}</div></section>
 <section className="clarity-examples" aria-labelledby="clarity-examples-heading"><div className="tool-section-heading"><p className="journal-label">For your business. For your own name.</p><h2 id="clarity-examples-heading">What could you do<br/>with the result?</h2><p>These fictional situations show how to use a priority. Your own answers determine your report.</p></div><div className="clarity-example-grid"><article><p className="journal-label">An independent business</p><h3>Make the purchase easier to understand.</h3><p>A consultant has described the benefits of a service but left its scope unclear. If Offer becomes a priority, they can start by putting the deliverables, buyer responsibilities and next step on one page.</p><p className="clarity-example-output"><strong>Something to work on:</strong> a service outline a prospect can read and question.</p></article><article><p className="journal-label">A personal brand</p><h3>Connect your experience to a specific need.</h3><p>A coach lists several areas of expertise without naming who the current offer serves. If Audience becomes a priority, they can describe one customer situation and investigate it in conversations.</p><p className="clarity-example-output"><strong>Something to work on:</strong> a clearer profile introduction and a customer question to test.</p></article></div><p className="clarity-example-note">The assessment provides authored guidance based on your answers. You create the copy, have the conversations and check what changes.</p></section>
 <section className="clarity-journey" id="how-it-works"><div><p className="journal-label">From a question to your next step</p><h2>How the assessment works.</h2><p>No timer and no pressure to choose a perfect answer. Every question includes a plain-language explanation and an example.</p><ol><li><span>01</span><div><h3>Reflect on your offer</h3><p>Answer 24 questions in six short sections. Save your progress and return when it suits you.</p></div></li><li><span>02</span><div><h3>Make sense of your answers</h3><p>See your six scores, three priorities and the answers behind them. Download your full PDF.</p></div></li><li><span>03</span><div><h3>Put your next moves to work</h3><p>Use the seven-day plan, then retake and compare. Your purchase keeps working for you.</p></div></li></ol></div><div className="clarity-question-card"><p className="journal-label">Try the feel of a question</p><fieldset><legend>{BRAND_QUESTIONS[0].prompt}</legend><details className="question-hint"><summary><span aria-hidden="true">i</span>What does this mean? See an example</summary><div><p>{BRAND_QUESTIONS[0].hint}</p><p><strong>For example</strong><br/>{BRAND_QUESTIONS[0].example}</p></div></details>{BRAND_QUESTIONS[0].options.map((option,index)=><label key={option}><input type="radio" name="sample-question" value={index}/><span>{option}</span></label>)}</fieldset><p className="tool-tax-note">This free preview is not saved. The full assessment takes about 10 minutes.</p></div></section>
 <section className="clarity-purchase-panel"><div><p className="journal-label">Less guessing. A clearer next move.</p><h2>A small investment.<br/>A tool to keep.</h2><p>You do not need another vague verdict about your potential. You need a useful view of what is clear, what needs evidence, and where to begin.</p><ul className="tool-inclusions"><li>24 questions with explanations and real-world examples</li><li>Six visual scores and three answer-based priorities</li><li>A seven-day action plan and downloadable PDF</li><li>Lifetime access, unlimited retakes and saved history</li><li>Side-by-side comparisons of any two saved reports</li></ul><Link href="/tools/brand-clarity/sample" className="tool-text-link">See the full sample before you buy ↗</Link></div><aside><p className="journal-label">Yours. Today and whenever you return.</p><AssessmentCheckout enabled={enabled} email={user?.email} ownedOrderId={owned?.status==="paid"?owned.id:undefined}/></aside></section>
 <section className="tool-faq" id="assessment-questions"><div className="tool-section-heading"><p className="journal-label">Before you begin</p><h2>Brand Clarity Assessment questions.</h2></div>{[
 ["Can I use it for a personal brand?","Yes, when your name represents a service or offer. Assess one offer at a time, such as a coaching engagement, consulting service or workshop. The questions concern the business you present to customers; they do not measure your personality or personal worth."],
 ["Do I need an established business or a website?","You can assess a new or existing offer without a website. For a new business, answer honestly about what you have defined and tested. Missing evidence is a useful starting point, not a reason to select a stronger answer. The assessment cannot validate demand for a new idea."],
 ["How is this different from a brand audit?","A full brand audit may inspect your materials and investigate customer perceptions. This assessment is a guided self-review of your own answers. It helps you prioritize what to examine next, but does not independently inspect your business or replace customer research."],
 ["What will I receive?","Your next three moves, a seven-day clarity plan and a visual report across six dimensions: audience, offer, difference, proof, message and visibility. You can download each report as a PDF, retake anytime and compare any two saved reports."],
 ["What does lifetime access mean?","Pay $9 USD once for ongoing access to this assessment, unlimited personal retakes and your saved report history for as long as CoachRank operates the service. There is no recurring fee and no 30-day expiry. Existing buyers receive the same upgrade. Download your PDFs to keep an independent copy."],
 ["What happens after I pay?","Once Dodo confirms payment, your assessment opens in this browser. Complete six short sections to see your report. Your purchase is saved to the account you signed in with. Open My tools on any device using Google or an email sign-in link with the same email. You do not need to purchase again."],
 ["Can I save progress and get help with a question?","Yes. Progress saves after each section, and Save progress or Save & exit is available while answering. Every question has an explanation and an example that you can open when you need it. There is no timer."],
 ["How are the recommendations personalized?","Your answers determine six scores and three priority dimensions. We show an answer behind each priority and build a seven-day plan from those areas. The guidance is authored by CoachRank and uses transparent scoring; no AI provider receives your answers."],
 ["Is this a scientifically validated test?","No. This is an original business self-assessment for reflection and prioritization, not a psychometric instrument, independent brand audit or prediction of revenue. Use it alongside customer conversations and real evidence. Higher scores are not a guarantee of better commercial outcomes."],
 ["What if I cannot access my purchase?","Sign in to My tools using the email connected to your purchase. For an earlier purchase, use the Missing an earlier purchase section to connect your private link or Dodo payment ID. Email contact@coachrank.lol with your receipt if you need help. If the product cannot be delivered, contact us for a resolution or refund; applicable consumer rights remain unaffected."]
 ].map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>
 {guides.some(Boolean)?<section className="clarity-reading" aria-labelledby="clarity-reading-heading"><div className="tool-section-heading"><p className="journal-label">Start with a useful idea</p><h2 id="clarity-reading-heading">Practical brand clarity guides.</h2><p>Free exercises to help you define, explain and examine your offer.</p></div><div>{guides.map(guide=>guide?<Link key={guide.id} href={`/blog/${guide.slug}`}><span>{guide.title}</span><span aria-hidden="true">↗</span></Link>:null)}</div></section>:null}
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(structured)}}/></div>;
}
