import Link from "next/link";
import { AssessmentCheckout } from "@/components/AssessmentCheckout";
import { BRAND_DIMENSIONS, BRAND_QUESTIONS } from "@/lib/brand-assessment";
import { absoluteUrl } from "@/lib/config";
import { isAssessmentCheckoutConfigured } from "@/lib/dodo";
import { jsonLd } from "@/lib/editorial";

export const dynamic = "force-dynamic";
export const metadata = { title: "Brand Clarity Assessment | $9", description: "Discover your brand gaps in 24 questions. Get six visual scores, three priorities, a seven-day action plan and one reassessment within 30 days. $9 USD, one time.", alternates: { canonical: "/tools/brand-clarity" }, openGraph: { title: "Find your brand gaps · CoachRank", url: absoluteUrl("/tools/brand-clarity") } };

export default async function BrandClarityPage({ searchParams }: PageProps<"/tools/brand-clarity">) {
  const enabled = isAssessmentCheckoutConfigured();
  const { checkout } = await searchParams;
  const structured = { "@context": "https://schema.org", "@type": "Product", name: "CoachRank Brand Clarity Assessment", description: "An original 24-question business self-assessment with six dimension scores, three priorities and a seven-day action plan.", brand: { "@type": "Brand", name: "CoachRank" }, image: absoluteUrl("/editorial/growth.webp"), offers: { "@type": "Offer", price: "9.00", priceCurrency: "USD", availability: enabled ? "https://schema.org/InStock" : "https://schema.org/OutOfStock", url: absoluteUrl("/tools/brand-clarity") } };
  return <div className="tools-shell"><Link href="/tools" className="tool-back">← CoachRank Tools</Link>{checkout === "cancelled" ? <p className="tool-notice" role="status">Checkout was closed. If you completed a payment, use “Already purchased?” below to check its status.</p> : null}<header className="assessment-hero"><div><p className="journal-label">Brand Clarity Assessment · Edition 01</p><h1>Your work deserves<br />a <em>clearer story.</em></h1><p className="assessment-dek">Find the gaps making your brand harder to understand and know what to fix first.</p><p className="assessment-audience">For coaches, consultants, founders and independent professionals with an offer to clarify.</p><div className="tool-product-facts"><span>24 questions</span><span>About 10 minutes</span><span>Personalized priorities</span></div><Link href="/tools/brand-clarity/sample" className="tool-text-link">See exactly what your report includes ↗</Link></div><aside><p className="journal-label">Clarity you can put to work</p><h2>One assessment.<br />A useful next move.</h2><ul className="tool-inclusions"><li>Six dimension scores and a visual dashboard</li><li>Your three priorities, explained through your answers</li><li>A seven-day action plan with concrete deliverables</li><li>A professionally formatted, downloadable PDF report</li><li>One reassessment within 30 days of your first report</li></ul><AssessmentCheckout enabled={enabled} /></aside></header>
  <section className="tool-dimensions"><div className="tool-section-heading"><p className="journal-label">Six dimensions of a clearer brand</p><h2>Find the missing pieces.</h2><p>Reflect on the evidence behind your brand: what you know, what you have tested and what a customer can actually see.</p></div><div>{BRAND_DIMENSIONS.map((dimension,index)=><article key={dimension.id}><span>0{index+1}</span><h3>{dimension.label}</h3><p>{dimension.subtitle}</p></article>)}</div></section>
  <section className="tool-question-preview"><div><p className="journal-label">A question from the assessment</p><h2>Specific questions.<br />Honest answers.</h2><p>Choose the answer that best describes your business today. An early-stage answer is useful information, not a verdict on your potential.</p><p>The report uses an original, transparent scoring guide. It is a business reflection tool, rather than a validated psychometric test or independent audit.</p></div><fieldset><legend>{BRAND_QUESTIONS[0].prompt}</legend>{BRAND_QUESTIONS[0].options.map((option,index)=><label key={option}><input type="radio" name="sample-question" value={index} /><span>{option}</span></label>)}<p>This preview is free and is not saved.</p></fieldset></section>
  <section className="tool-faq"><div className="tool-section-heading"><p className="journal-label">Before you begin</p><h2>A few clear answers.</h2></div>{[
    ["What happens after I pay?", "Once Dodo confirms your payment, your assessment opens in this browser. You answer six short sections and get your report immediately after completing all 24 questions. Save your private access link to return on another device."],
    ["Can I save my progress?", "Yes. Progress is saved to your private assessment after each section, and you can use Save & exit at any time. Keep your private access link: anyone with it can access your answers and report."],
    ["How is the report personalized?", "Your answers determine your six scores and three priority dimensions. The report cites an answer behind each priority and builds a seven-day plan from those areas. Recommendations come from CoachRank's written guidance; no AI service receives your answers."],
    ["Can I take it again?", "Your purchase includes your initial report and one reassessment completed within 30 days of the first report. The second report compares the two sets of scores. You can keep returning to saved reports afterward while the service remains available."],
    ["Will this define my entire brand?", "It helps you identify gaps and choose what to work on. It does not create a logo, independently evaluate your business, predict revenue or replace customer research."],
    ["What if I cannot access my purchase?", "Use your saved private access link, or contact contact@coachrank.lol with your Dodo receipt. We can help restore access. If the product cannot be delivered, contact us for a resolution or refund; applicable consumer rights remain unaffected."],
  ].map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(structured) }} /></div>;
}
