import Link from "next/link";
import {AssessmentCheckout} from "@/components/AssessmentCheckout";
import {ReportPreview} from "@/components/ReportPreview";
import {DimensionIcon} from "@/components/DimensionIcon";
import {BRAND_DIMENSIONS,BRAND_QUESTIONS} from "@/lib/brand-assessment";
import {absoluteUrl} from "@/lib/config";
import {isAssessmentCheckoutConfigured} from "@/lib/dodo";
import {getCustomerUser} from "@/lib/customer-auth";
import {customerAssessment} from "@/lib/domain/assessments";
import {jsonLd} from "@/lib/editorial";
export const dynamic="force-dynamic";
export const metadata={title:"Brand Clarity Assessment | $9 Lifetime Access",description:"Get your next three moves, a seven-day clarity plan and a visual brand report. Pay $9 once, retake anytime and compare saved reports. Includes a PDF download.",alternates:{canonical:"/tools/brand-clarity"},openGraph:{title:"Your next three brand moves, made clear · CoachRank",url:absoluteUrl("/tools/brand-clarity")}};
export default async function BrandClarityPage({searchParams}:PageProps<"/tools/brand-clarity">){
 const enabled=isAssessmentCheckoutConfigured();const {checkout}=await searchParams;
 const user=await getCustomerUser();const owned=user?await customerAssessment(user.uid):null;
 const structured={"@context":"https://schema.org","@type":"Product",name:"CoachRank Brand Clarity Assessment",description:"24 questions, six visual scores, three next moves, a seven-day plan and a downloadable PDF. Lifetime access with unlimited retakes and report comparisons.",brand:{"@type":"Brand",name:"CoachRank"},image:absoluteUrl("/editorial/growth.webp"),offers:{"@type":"Offer",price:"9.00",priceCurrency:"USD",availability:enabled?"https://schema.org/InStock":"https://schema.org/OutOfStock",url:absoluteUrl("/tools/brand-clarity")}};
 return <div className="tools-shell clarity-page"><Link href="/tools" className="tool-back">← CoachRank Tools</Link>{checkout==="cancelled"?<p className="tool-notice" role="status">Checkout was closed. Already paid? Open My tools below to check your purchase.</p>:null}
 <header className="clarity-hero"><div className="clarity-hero-copy"><p className="journal-label"><span className="journal-status-dot"/>Brand Clarity Assessment · Edition 01</p><h1>Know where you are.<br/><em>Know your next<br className="clarity-desktop-break"/> three moves.</em></h1><p className="clarity-dek">A visual picture of your brand, three priorities worth acting on, and a seven-day clarity plan. Yours to revisit as your business grows.</p><p className="clarity-audience">For coaches, consultants, founders and independent professionals with an offer to clarify.</p><div className="clarity-hero-actions"><a href="#get-assessment" className="tool-button">Get lifetime access · $9 ↗</a><Link href="/tools/brand-clarity/sample" className="tool-text-link">Explore a complete report</Link></div><div className="clarity-purchase-facts"><span>✓ Pay once</span><span>✓ Unlimited retakes</span><span>✓ Compare your reports</span></div><p className="tool-tax-note">$9 USD plus applicable tax. No subscription.</p></div><ReportPreview/></header>
 <section className="clarity-outcomes" aria-label="What your purchase includes"><article><span className="outcome-symbol" aria-hidden="true">↗</span><p className="journal-label">01 / Direction</p><h2>Your next three moves.</h2><p>Understand which gaps deserve attention first, with an answer behind each priority and a concrete action to take.</p></article><article><span className="outcome-symbol" aria-hidden="true">7</span><p className="journal-label">02 / A plan</p><h2>A week with a purpose.</h2><p>Seven work sessions, each with a task and something useful to leave with. Download the report and keep it beside your work.</p></article><article><span className="outcome-symbol" aria-hidden="true">∞</span><p className="journal-label">03 / Perspective</p><h2>Return. Reflect. Compare.</h2><p>Retake whenever you have new evidence. Keep every report and compare any two snapshots side by side.</p></article></section>
 <section className="tool-dimensions"><div className="tool-section-heading"><p className="journal-label">Six dimensions of a clearer brand</p><h2>Find the missing pieces.</h2><p>A useful brand is more than how it looks. Explore the evidence behind what you say, sell and share.</p></div><div>{BRAND_DIMENSIONS.map(d=><article key={d.id}><DimensionIcon dimension={d.id}/><h3>{d.label}</h3><p>{d.subtitle}</p></article>)}</div></section>
 <section className="clarity-journey"><div><p className="journal-label">From a question to your next step</p><h2>Thoughtful by design.<br/>Simple to use.</h2><p>No jargon test. No timer. No pressure to choose a perfect answer. Every question includes a plain-language explanation and an example.</p><ol><li><span>01</span><div><h3>Reflect on your offer</h3><p>Answer 24 questions in six short sections. Save your progress and return when it suits you.</p></div></li><li><span>02</span><div><h3>Make sense of your answers</h3><p>See your six scores, three priorities and the evidence behind them. Download your full PDF.</p></div></li><li><span>03</span><div><h3>Put your next moves to work</h3><p>Use the seven-day plan, then retake and compare. Your purchase keeps working for you.</p></div></li></ol></div><div className="clarity-question-card"><p className="journal-label">Try the feel of a question</p><fieldset><legend>{BRAND_QUESTIONS[0].prompt}</legend><details className="question-hint"><summary><span aria-hidden="true">i</span>What does this mean? See an example</summary><div><p>{BRAND_QUESTIONS[0].hint}</p><p><strong>For example</strong><br/>{BRAND_QUESTIONS[0].example}</p></div></details>{BRAND_QUESTIONS[0].options.map((option,index)=><label key={option}><input type="radio" name="sample-question" value={index}/><span>{option}</span></label>)}</fieldset><p className="tool-tax-note">This free preview is not saved. The full assessment takes about 10 minutes.</p></div></section>
 <section className="clarity-purchase-panel"><div><p className="journal-label">Less guessing. A clearer next move.</p><h2>A small investment.<br/>A tool to keep.</h2><p>You do not need another vague verdict about your potential. You need a useful view of what is clear, what needs evidence, and where to begin.</p><ul className="tool-inclusions"><li>24 questions with explanations and real-world examples</li><li>Six visual scores and three answer-based priorities</li><li>A seven-day action plan and downloadable PDF</li><li>Lifetime access, unlimited retakes and saved history</li><li>Side-by-side comparisons of any two saved reports</li></ul><Link href="/tools/brand-clarity/sample" className="tool-text-link">See the full sample before you buy ↗</Link></div><aside><p className="journal-label">Yours. Today and whenever you return.</p><AssessmentCheckout enabled={enabled} email={user?.email} ownedOrderId={owned?.status==="paid"?owned.id:undefined}/></aside></section>
 <section className="tool-faq"><div className="tool-section-heading"><p className="journal-label">Before you begin</p><h2>A few clear answers.</h2></div>{[
 ["What will I receive?","Your next three moves, a seven-day clarity plan and a visual report across six dimensions: audience, offer, difference, proof, message and visibility. You can download each report as a PDF, retake anytime and compare any two saved reports."],
 ["What does lifetime access mean?","Pay $9 USD once for ongoing access to this assessment, unlimited personal retakes and your saved report history for as long as CoachRank operates the service. There is no recurring fee and no 30-day expiry. Existing buyers receive the same upgrade. Download your PDFs to keep an independent copy."],
 ["What happens after I pay?","Once Dodo confirms payment, your assessment opens in this browser. Complete six short sections to see your report. Your purchase is saved to the account you signed in with. Open My tools on any device using Google or an email sign-in link with the same email. You do not need to purchase again."],
 ["Can I save progress and get help with a question?","Yes. Progress saves after each section, and Save progress or Save & exit is available while answering. Every question has an explanation and an example that you can open when you need it. There is no timer."],
 ["How are the recommendations personalized?","Your answers determine six scores and three priority dimensions. We show an answer behind each priority and build a seven-day plan from those areas. The guidance is authored by CoachRank and uses transparent scoring; no AI provider receives your answers."],
 ["Is this a scientifically validated test?","No. This is an original business self-assessment for reflection and prioritization, not a psychometric instrument, independent brand audit or prediction of revenue. Use it alongside customer conversations and real evidence. Higher scores are not a guarantee of better commercial outcomes."],
 ["What if I cannot access my purchase?","Sign in to My tools using the email connected to your purchase. For an earlier purchase, use the Missing an earlier purchase section to connect your private link or Dodo payment ID. Email contact@coachrank.lol with your receipt if you need help. If the product cannot be delivered, contact us for a resolution or refund; applicable consumer rights remain unaffected."]
 ].map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(structured)}}/></div>;
}
