/** Outlined CoachRank wordmark. No installed fonts are required to use the exports. */
import {mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import * as fontkit from 'fontkit';
import sharp from 'sharp';
const root=process.cwd(),dir=join(root,'public/brand');mkdirSync(dir,{recursive:true});
const font=fontkit.openSync(join(root,'assets/fonts/bricolage-grotesque-800.woff2'));
const run=font.layout('CoachRank.');let x=20;
const paths=run.glyphs.map((glyph,i)=>{const result={d:glyph.path.toSVG(),x:x+run.positions[i].xOffset,dot:i===run.glyphs.length-1};x+=run.positions[i].xAdvance-34;return result;});
const bounds=run.glyphs.map((glyph,i)=>({minX:paths[i].x+glyph.bbox.minX,maxX:paths[i].x+glyph.bbox.maxX,minY:755-glyph.bbox.maxY,maxY:755-glyph.bbox.minY}));
const inkBounds={x:Math.min(...bounds.map(b=>b.minX)),y:Math.min(...bounds.map(b=>b.minY)),width:Math.max(...bounds.map(b=>b.maxX))-Math.min(...bounds.map(b=>b.minX)),height:Math.max(...bounds.map(b=>b.maxY))-Math.min(...bounds.map(b=>b.minY))};
const geometry={width:Math.ceil(x+30),height:810,baseline:755,inkBounds,paths};
writeFileSync(join(root,'src/lib/brand-wordmark.ts'),'// Generated by scripts/generate-brand.mjs from the licensed Bricolage font.\nexport const WORDMARK = '+JSON.stringify(geometry)+' as const;\n');
function inner(ink,accent){return paths.map(p=>`<path d="${p.d}" transform="translate(${p.x} 755) scale(1 -1)" fill="${p.dot?accent:ink}"/>`).join('');}
function wordmark(ink='#101218',accent='#2C4BF0',bg){return `<svg xmlns="http://www.w3.org/2000/svg" width="${geometry.width}" height="810" viewBox="0 0 ${geometry.width} 810" role="img" aria-label="CoachRank.">${bg?`<rect width="100%" height="100%" fill="${bg}"/>`:''}${inner(ink,accent)}</svg>`;}
const variants=[['wordmark','#101218','#2C4BF0'],['wordmark-dark','#F2F3F6','#9BA8FF'],['wordmark-white','#FFFFFF','#FFFFFF'],['wordmark-black','#101218','#101218']];
for(const[name,ink,accent]of variants){const svg=wordmark(ink,accent);writeFileSync(join(dir,name+'.svg'),svg);writeFileSync(join(dir,name+'.png'),await sharp(Buffer.from(svg)).resize({width:2400}).png().toBuffer());}
// Square avatars keep the complete name in the safe center of a circular crop.
function avatar(bg,ink,accent){const w=800,h=w*810/geometry.width;return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="${bg}"/><g transform="translate(112 ${(1024-h)/2}) scale(${w/geometry.width})">${inner(ink,accent)}</g></svg>`;}
for(const[name,bg,ink,accent]of [['avatar','#FBFAF7','#101218','#2C4BF0'],['avatar-dark','#0C0D10','#F2F3F6','#9BA8FF'],['avatar-blue','#2C4BF0','#FFFFFF','#FFFFFF']]){const svg=avatar(bg,ink,accent);writeFileSync(join(dir,name+'.svg'),svg);for(const size of [1024,512])writeFileSync(join(dir,`${name}-${size}.png`),await sharp(Buffer.from(svg)).resize(size).png().toBuffer());}
// C. is a typographic micro version for favicon sizes where a whole name is illegible.
const c=font.layout('C.');let cx=90;const micro=c.glyphs.map((g,i)=>{const p=`<path d="${g.path.toSVG()}" transform="translate(${cx} 850) scale(1 -1)" fill="${i?'#2C4BF0':'#101218'}"/>`;cx+=c.positions[i].xAdvance-30;return p;}).join('');
const icon=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 1100"><rect width="1100" height="1100" rx="220" fill="#FBFAF7"/>${micro}</svg>`;
writeFileSync(join(root,'src/app/icon.svg'),icon);writeFileSync(join(root,'src/app/apple-icon.png'),await sharp(Buffer.from(icon)).resize(180).png().toBuffer());writeFileSync(join(dir,'favicon.svg'),icon);writeFileSync(join(dir,'mark.svg'),wordmark());
const banner=`<svg xmlns="http://www.w3.org/2000/svg" width="1500" height="500" viewBox="0 0 1500 500"><rect width="1500" height="500" fill="#FBFAF7"/><g transform="translate(410 120) scale(${760/geometry.width})">${inner('#101218','#2C4BF0')}</g><text x="420" y="335" font-family="sans-serif" font-size="27" fill="#545861">Celebrating greatness. Understanding what builds it.</text><circle cx="1380" cy="400" r="200" fill="#2C4BF0" opacity=".055"/></svg>`;
writeFileSync(join(dir,'x-header-1500x500.png'),await sharp(Buffer.from(banner)).png().toBuffer());
writeFileSync(join(dir,'README.md'),`# CoachRank brand kit\n\nThe complete CoachRank wordmark with its blue dot is the primary identity.\n\n- wordmark.svg / wordmark.png: transparent, dark lettering for light backgrounds.\n- wordmark-dark.svg / wordmark-dark.png: transparent, light lettering for dark backgrounds.\n- wordmark-white and wordmark-black: single-color artwork.\n- avatar-1024.png: complete name, centered for X and other circular profile crops.\n- avatar-dark-1024.png and avatar-blue-1024.png: alternate profile backgrounds.\n- x-header-1500x500.png: social cover with space on the left for the profile overlap.\n- favicon.svg: C. micro wordmark, used only when the full name would be too small.\n\nSVG lettering is outlined. It will not change font on another computer. Do not stretch, add a separate icon, change letter spacing, or remove the dot. Keep space around the wordmark.\n\nTypeface: Bricolage Grotesque, SIL Open Font License. Source and license in assets/fonts. Regenerate using node scripts/generate-brand.mjs.\n`);
console.log('Generated outlined wordmarks, social avatars, X header and typographic favicon.');
